[package]
name = "terra_forge"
version = "0.1.0"
edition = "2021"

[dependencies]
spade = "2.9.0"
console_log = "1.0.0"
serde = "1.0.201"
serde_json = "1.0.116"
tokio = { version = "1.37.0", features = ["rt", "net", "rt-multi-thread"] }
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
